Controllers/BidsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuthOnlineApp.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis;

namespace AuthOnlineApp.Controllers
{
    public class BidsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BidsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Bids
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var items = _context.Bid
                    .Include(b => b.Product).Include(b => b.User);
                return View(await items.ToListAsync());
            }
            else
            {
                var userId = (await _userManager.GetUserAsync(User)).Id;
                var items = _context.Bid
                    .Where(item => item.UserId == userId)
                    .Include(b => b.Product).Include(b => b.User);
                return View(await items.ToListAsync());
            }
        }

        // GET: Bids/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bid = await _context.Bid
                .Include(b => b.Product)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.BidId == id);
            if (bid == null)
            {
                return NotFound();
            }

            return View(bid);
        }

        // GET: Bids/Create
        [Authorize]
        public async Task<IActionResult> CreateAsync(int productId)
        {
            var product = await _context.Product.FindAsync(productId);
            var user = await _userManager.GetUserAsync(User);

            if (product == null)
            {
                return NotFound();
            }

            if (product.CreatedByUserId == user.Id)
            {
                return Forbid();
            }

            ViewData["ProductId"] = new SelectList(_context.Set<Product>()
                .Where(item => item.Deadline > DateTime.Now), "ProductId", "Name", productId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", user.Id);
            return View();
        }

        [Authorize]
        // POST: Bids/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BidId,Amount,CreatedAt,ProductId,UserId")] Bid bid)
        {
            if (ModelState.IsValid)
            {
                var product = _context.Product.Find(bid.ProductId);
                var user = await _userManager.GetUserAsync(User);

                
                if (product.CreatedByUserId == user.Id)
                {
                    return Forbid();
                }

                var startingPrice = product.StartingPrice;
                if (bid.Amount <= startingPrice)
                {
                    ModelState.AddModelError("Amount", "Amount should be at least equal to starting price.");
                }
                else
                {
                    _context.Add(bid);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Name", bid.ProductId);
            var userId = (await _userManager.GetUserAsync(User)).Id;
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userId);
            return View();
        }

        // GET: Bids/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bid = await _context.Bid.FindAsync(id);
            if (bid == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Name", bid.ProductId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", bid.UserId);
            return View(bid);
        }

        // POST: Bids/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BidId,Amount,CreatedAt,ProductId,UserId")] Bid bid)
        {
            if (id != bid.BidId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BidExists(bid.BidId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Name", bid.ProductId);
            var userId = (await _userManager.GetUserAsync(User)).Id;
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userId);
            return View(bid);
        }

        // GET: Bids/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bid = await _context.Bid
                .Include(b => b.Product)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.BidId == id);
            if (bid == null)
            {
                return NotFound();
            }

            return View(bid);
        }

        // POST: Bids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bid = await _context.Bid.FindAsync(id);
            if (bid != null)
            {
                _context.Bid.Remove(bid);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BidExists(int id)
        {
            return _context.Bid.Any(e => e.BidId == id);
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuthOnlineApp.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration.UserSecrets;

namespace AuthOnlineApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProductsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Products
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var items = _context.Bid
                    .Include(b => b.Product).Include(b => b.User);
                return View(await items.ToListAsync());
            }
            else
            {
                var userId = (await _userManager.GetUserAsync(User)).Id;
                var applicationDbContext = _context.Product
                    .Where(item => item.CreatedByUserId == userId)
                    .Include(p => p.CreatedByUser);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.CreatedByUser)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize]
        // GET: Products/Create
        public async Task<IActionResult> CreateAsync()
        {
            var userId = (await _userManager.GetUserAsync(User)).Id;
            ViewData["CreatedByUserId"] = new SelectList(_context.Users, "Id", "Id", userId);
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var userId = (await _userManager.GetUserAsync(User)).Id;
            ViewData["CreatedByUserId"] = new SelectList(_context.Users, "Id", "Id", userId);
            return View(product);
        }
        [Authorize]
        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = (await _userManager.GetUserAsync(User)).Id;
            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            if(product.CreatedByUserId != userId && !User.IsInRole("Admin"))
            {
                return Unauthorized();
            }
            ViewData["CreatedByUserId"] = new SelectList(_context.Users, "Id", "Id", product.CreatedByUserId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreatedByUserId"] = new SelectList(_context.Users, "Id", "Id", product.CreatedByUserId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.CreatedByUser)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trust Market</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthOnlineApp.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet" />

    <style>
        html, body {
            height: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
        }

        .wrapper {
            flex: 1;
            display: flex;
            flex-direction: column;
        }

        body {
            background: #f8f9fa;
            font-family: 'Arial', sans-serif;
        }

        .custom-navbar {
            background: linear-gradient(90deg, #4b4b4b, #1c1c1c);
            padding: 0.75rem 1rem;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 1.75rem;
            color: #fff !important;
            letter-spacing: 1px;
        }

        .navbar-nav .nav-link {
            color: #fff; /* Default text color */
            transition: color 0.3s;
            padding: 10px 20px;
            border-radius: 6px;
        }

            .navbar-nav .nav-link:hover,
            .navbar-nav .nav-link.active {
                background-color: #007bff; 
                color: white; 
            }

        .profile-section {
            background-color: #007bff;
            color: white;
            padding: 50px 0;
            text-align: center;
            margin-bottom: 50px;
        }

            .profile-section .profile-pic {
                border-radius: 50%;
                width: 120px;
                height: 120px;
                object-fit: cover;
                margin-bottom: 15px;
            }

            .profile-section h2 {
                margin-bottom: 20px;
            }

            .profile-section .username {
                font-size: 1.5rem;
                font-weight: 600;
            }

        .container {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .card {
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease;
        }

            .card:hover {
                transform: translateY(-5px);
            }

        .card-body {
            background-color: white;
            padding: 20px;
        }

        .card-title {
            font-size: 1.25rem;
            font-weight: 600;
        }

        .btn-custom {
            font-size: 14px;
            padding: 8px 15px;
            border-radius: 5px;
        }

        footer {
            background-color: #343a40;
            color: white;
            text-align: center;
            padding: 15px 0;
            margin-top: 60px;
        }

        .navbar-nav .btn {
            padding: 6px 14px;
            font-size: 0.9rem;
            border-radius: 6px;
            margin-left: 8px;
        }

        .auth-buttons {
            display: flex;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-dark custom-navbar">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trust Market</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <!-- Made these links look like buttons with the .btn-primary class -->
                            <li class="nav-item">
                                <a class="btn btn-primary text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary text-white" asp-area="" asp-controller="Products" asp-action="Index">My Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary text-white" asp-area="" asp-controller="Bids" asp-action="Index">My Bids</a>
                            </li>
                        </ul>

                        <!-- Auth buttons -->
                        <ul class="navbar-nav auth-buttons">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="btn btn-primary text-white" asp-area="Identity" asp-page="/Account/Manage/Index">
                                        <i class="bi bi-person-circle"></i> @User.Identity.Name
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="d-inline">
                                        <button type="submit" class="btn btn-primary text-white">
                                            <i class="bi bi-box-arrow-right"></i> Logout
                                        </button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="btn btn-primary text-white" asp-area="Identity" asp-page="/Account/Register">
                                        <i class="bi bi-person-plus"></i> Register
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-primary text-white" asp-area="Identity" asp-page="/Account/Login">
                                        <i class="bi bi-box-arrow-in-right"></i> Login
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        @if (ViewData["ShowDashboard"] != null && (bool)ViewData["ShowDashboard"] == true)
        {
            <section class="profile-section">
                <h2>Welcome</h2>
                <p class="username">@User.Identity.Name</p>
                <div class="col-md-12 text-center mb-4">
                    <a asp-controller="Products" asp-action="Create" class="btn btn-secondary btn-lg text-white">
                        <i class="bi bi-plus-circle"></i> Create New Product
                    </a>
                </div>
            </section>
        }

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer>
        <div class="container">
            &copy; 2025 - Trust Market -
            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>